### ISSUE TITLE
[BUG] Unclean termination of ModelatorShell when checker is TLC

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#195]
The following sequence of commands 

```sh
python3 -I modelator_shell.py
>>> m = ModelatorShell()
>>> m.load('modelator/samples/Hello.tla')
>>> m.check(checker='tlc')
Check error at modelator/samples/Hello.tla:
Invariant Inv violated.
Counterexample is [(x = "hello") /\ (y = 22), (x = "world") /\ (y = 20)]
>>> exit()
```

leads to an exception on exiting from Python shell:
```
Exception ignored in: <function Pool.__del__ at 0x104e84e50>
Traceback (most recent call last):
  File "/Users/andrey/Library/Caches/pypoetry/virtualenvs/modelator-WKAzkonN-py3.10/lib/python3.10/site-packages/multiprocess/pool.py", line 268, in __del__
  File "/Users/andrey/Library/Caches/pypoetry/virtualenvs/modelator-WKAzkonN-py3.10/lib/python3.10/site-packages/multiprocess/queues.py", line 375, in put
  File "/Users/andrey/Library/Caches/pypoetry/virtualenvs/modelator-WKAzkonN-py3.10/lib/python3.10/site-packages/multiprocess/reduction.py", line 54, in dumps
  File "/Users/andrey/Library/Caches/pypoetry/virtualenvs/modelator-WKAzkonN-py3.10/lib/python3.10/site-packages/multiprocess/reduction.py", line 42, in __init__
  File "/Users/andrey/Library/Caches/pypoetry/virtualenvs/modelator-WKAzkonN-py3.10/lib/python3.10/site-packages/dill/_dill.py", line 573, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by rnbguy** [comment]
I noticed this in CI too. Most likely it comes from here `modelator-py`.

https://github.com/informalsystems/modelator-py/blob/62e8f3bdf5a8060f6b85c2bba28799c187b57ce8/modelator_py/helper.py#L46-L55

Probably some exception is raised when applying the parallel map - which led to some undefined behaviors.
